apiVersion: 1

datasources:
  - name: prometheus
    uid: prometheus
    type: prometheus
    url: http://prometheus-server.monitoring.svc.cluster.local:9090
    access: proxy
    isDefault: true
  - name: alertmanager
    uid: alertmanager
    type: alertmanager
    url: http://prometheus-alertmanager.monitoring.svc.cluster.local:9093
    access: proxy
    isDefault: false
    # jsonData:
    #   httpMethod: POST
    #   tlsSkipVerify: true
    #   timeInterval: "10s"