image:
  registry: docker.io
  repository: bitnami/node-exporter
  tag: 1.9.1-debian-12-r11
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []

containerPorts:
  metrics: 9100

service:
  type: ClusterIP
  ports:
    metrics: 9100

resourcesPreset: "nano"
