    apiVersion: 1
    
    contactPoints:
      - orgId: 1
        name: devops
        receivers:
          - uid: devops
            type: email
            settings:
              addresses: jenkins.notify.lerkasan@gmail.com
              subject: "ALERT: {{ .GroupLabels.alertname }}"
              message: |
                {{ range .Alerts.Firing }}
                Alert: {{ .Annotations.summary }}
                Severity: {{ .Labels.severity }}                
                Description: {{ .Annotations.description }}
                Instance: {{ .Labels.instance }}
                Started: {{ .StartsAt }}
                {{ end }}
            disableResolveMessage: false
    
    policies:
      - orgId: 1
        receiver: devops
        group_by: ['alertname']
        group_wait: 10s
        group_interval: 5m
        repeat_interval: 4h
        routes:
          - receiver: devops
            matchers:
              - severity = high
            group_wait: 10s
            group_interval: 5m
            repeat_interval: 1h
          - receiver: devops
            matchers:
              - severity = critical
            group_wait: 5s
            group_interval: 2m
            repeat_interval: 30m            
    
    groups:
      - orgId: 1
        name: NodeAlerts
        folder: Infrastructure
        interval: 1m
        rules:
          - uid: node-out-of-memory
            title: Out Of Memory
            condition: A
            data:
              - refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: prometheus
                model:
                  expr: (100 * node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes < 10)
                  interval: 2m
                  legendFormat: "{{instance}}"
                  refId: A
            noDataState: NoData
            execErrState: Alerting
            for: 5m
            annotations:
              summary: 'Node {{ $labels.instance }} is running out of memory.'
              description: 'Memory is critically low (< 10% left) on {{ $labels.instance }}. Free memory left: {{ printf "%.2f" $value }}%.'
            labels:
              severity: high
              team: devops
            contactPoint: devops

          - uid: high-memory-usage
            title: High Memory Usage
            condition: A
            data:
              - refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: prometheus
                model:
                  expr: 100 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100) > 80
                  interval: 2m
                  legendFormat: "{{instance}}"
                  refId: A
            noDataState: NoData
            execErrState: Alerting
            for: 5m
            annotations:
              summary: 'Node {{ $labels.instance }} has high memory usage.'
              description: 'Node {{ $labels.instance }} is experiencing high memory usage above 80% for the last 5 minutes. Currently memory usage is at {{ printf "%.2f" $value }}%.'
            labels:
              severity: high
              team: devops
            contactPoint: devops              

          - uid: high-cpu-usage
            title: High CPU Usage
            condition: A
            data:
              - refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: prometheus
                model:
                  expr: sum without(mode) (avg without (cpu) (rate(node_cpu_seconds_total{mode!~"idle|iowait"}[2m]))) * 100 > 80
                  interval: 2m
                  legendFormat: "{{instance}}"
                  refId: A
            noDataState: NoData
            execErrState: Alerting
            for: 5m
            annotations:
              summary: 'High CPU usage at {{ $labels.instance }} node.'
              description: 'CPU usage at {{ $labels.instance }} has been above 80% for the last 5 minutes, is currently at {{ printf "%.2f" $value }}%.'
            labels:
              severity: high
              team: devops
            contactPoint: devops              
