    apiVersion: 1
    
    contactPoints:
      - orgId: 1
        name: devops
        receivers:
          - uid: devops
            type: email
            settings:
              addresses: jenkins.notify.lerkasan@gmail.com
              subject: "ALERT: {{ .GroupLabels.alertname }}"
              message: |
                {{ range .Alerts.Firing }}
                Alert: {{ .Annotations.summary }}
                Severity: {{ .Labels.severity }}                
                Description: {{ .Annotations.description }}
                Instance: {{ .Labels.instance }}
                Started: {{ .StartsAt }}
                {{ end }}
            disableResolveMessage: false
    
    policies:
      - orgId: 1
        receiver: devops
        group_by: ['alertname']
        group_wait: 10s
        group_interval: 5m
        repeat_interval: 4h
        routes:
          - receiver: devops
            matchers:
              - severity = high
            group_wait: 10s
            group_interval: 5m
            repeat_interval: 1h
          - receiver: devops
            matchers:
              - severity = critical
            group_wait: 5s
            group_interval: 2m
            repeat_interval: 30m

    groups:
      - orgId: 1
        name: testgroup
        folder: Infrastructure
        interval: 1m
        rules:
          - uid: node-out-of-memory
            title: node-out-of-memory
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: prometheus
                model:
                  editorMode: code
                  expr: 100 * node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes
                  instant: true
                  intervalMs: 1000
                  legendFormat: __auto
                  maxDataPoints: 43200
                  range: false
                  refId: A
              - refId: C
                datasourceUid: __expr__
                model:
                  conditions:
                      - evaluator:
                          params:
                              - 10
                          type: lt
                        operator:
                          type: and
                        query:
                          params:
                              - C
                        reducer:
                          params: []
                          type: last
                        type: query
                  datasource:
                      type: __expr__
                      uid: __expr__
                  expression: A
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: C
                  type: threshold
            noDataState: NoData
            execErrState: Error
            for: 3m
            keepFiringFor: 3m
            annotations:
              description: Memory is critically low (< 10% free) on {{ .Labels.instance }}.
              summary: Node {{ .Labels.instance }} is running out of memory.
            labels:
              severity: high
              team: devops
            isPaused: false
            notification_settings:
              receiver: devops
          - uid: high-memory-usage
            title: high-memory-usage
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: prometheus
                model:
                  editorMode: code
                  expr: 100 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100)
                  instant: true
                  intervalMs: 1000
                  legendFormat: __auto
                  maxDataPoints: 43200
                  range: false
                  refId: A
              - refId: C
                datasourceUid: __expr__
                model:
                  conditions:
                      - evaluator:
                          params:
                              - 80
                          type: gt
                        operator:
                          type: and
                        query:
                          params:
                              - C
                        reducer:
                          params: []
                          type: last
                        type: query
                  datasource:
                      type: __expr__
                      uid: __expr__
                  expression: A
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: C
                  type: threshold
            noDataState: NoData
            execErrState: Error
            for: 3m
            keepFiringFor: 3m
            annotations:
              description: Node {{ .Labels.instance }} is experiencing high memory usage above 80% for the last 5 minutes.
              summary: Node {{ .Labels.instance }} has high memory usage.
            labels:
              severity: high
              team: devops
            isPaused: false
            notification_settings:
              receiver: devops
          - uid: high-cpu-usage
            title: high-cpu-usage
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: prometheus
                model:
                  editorMode: code
                  expr: sum without(mode) (avg without (cpu) (rate(node_cpu_seconds_total{mode!~"idle|iowait"}[2m]))) * 100
                  instant: true
                  intervalMs: 1000
                  legendFormat: __auto
                  maxDataPoints: 43200
                  range: false
                  refId: A
              - refId: C
                datasourceUid: __expr__
                model:
                  conditions:
                      - evaluator:
                          params:
                              - 80
                          type: gt
                        operator:
                          type: and
                        query:
                          params:
                              - C
                        reducer:
                          params: []
                          type: last
                        type: query
                  datasource:
                      type: __expr__
                      uid: __expr__
                  expression: A
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: C
                  type: threshold
            noDataState: NoData
            execErrState: Error
            for: 3m
            keepFiringFor: 3m
            annotations:
              description: CPU usage at {{ .Labels.instance }} has been above 80% for the last 5 minutes.
              summary: High CPU usage at {{ .Labels.instance }} node.
            labels:
              severity: high
              team: devops
            isPaused: false
            notification_settings:
              receiver: devops
