apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  selector:
    {{- toYaml .Values.selectorLabels | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - name: http-port-{{ .Values.service.port }}
      protocol: TCP
      port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}